@startuml
skinparam dpi 180
class ControladorContenido
class ControladorModeracion
interface RepoApuntes
class Apunte {
  +agregarValoracion(usuario,puntaje)
  +agregarComentario(usuario,texto)
  +cambiarEstado(decision)
  +calcularPromedio()
}
class Valoracion
class Comentario
ControladorContenido --> RepoApuntes
ControladorContenido --> Apunte : coordina
Apunte o-- Valoracion
Apunte o-- Comentario
@enduml
