@startuml
title Notivium — Diagrama de Clases (Dominio)

' ——— Estilo
skinparam shadowing false
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam dpi 180
skinparam class {
  BackgroundColor #F7FAFF
  BorderColor #1D3B53
}
skinparam stereotypeCBackgroundColor #E6F0FF
skinparam stereotypeCBorderColor #1D3B53

' ——— Enums
enum EstadoApunte {
  PENDIENTE
  APROBADO
  RECHAZADO
}

enum TipoDecision {
  APROBAR
  RECHAZAR
}

' ——— Clases del dominio
class Usuario <<entity>> {
  +id: UUID
  +nombre: String
  +emailInstitucional: String
  +esAdmin(): Boolean
}

class Administrador <<entity>> {
  ' hereda credenciales y datos de Usuario
}

Usuario <|-- Administrador

class Apunte <<entity>> {
  +id: UUID
  +titulo: String
  +descripcion: String
  +fechaSubida: DateTime
  +estado: EstadoApunte
  --
  +calcularPromedio(): float
  +cambiarEstado(d: DecisionModeracion): void
}

class Comentario <<entity>> {
  +id: UUID
  +texto: String
  +fecha: DateTime
  --
  +ocultar(): void
}

class Valoracion <<entity>> {
  +id: UUID
  +puntaje: int  ' [1..5]
  +fecha: DateTime
}

class DecisionModeracion <<entity>> {
  +id: UUID
  +decision: TipoDecision
  +motivo: String
  +fecha: DateTime
}

' ——— Relaciones principales (cardinalidades y roles)
Usuario "1" --> "0..*" Apunte : crea >
Usuario "1" --> "0..*" Comentario : escribe >
Usuario "1" --> "0..*" Valoracion : emite >

Apunte "1" o-- "0..*" Comentario : contiene
Apunte "1" o-- "0..*" Valoracion : contiene

Administrador "1" --> "0..*" DecisionModeracion : aplica >
DecisionModeracion "1" --> "1" Apunte : modifica estado

' dueño de comentario/valoración (traza de autoría)
Comentario "0..*" --> "1" Usuario : autor
Valoracion "0..*" --> "1" Usuario : autor

' referencias explícitas al apunte (además de la composición)
Comentario "0..*" --> "1" Apunte
Valoracion "0..*" --> "1" Apunte

@enduml
